name: 🚀 新功能提議
description: New Feature Proposal | 新功能提議表單
labels: [enhancement, needs-discussion]
body:
  - type: markdown
    attributes:
      value: |
        這裡是新功能提議表單。

        填寫時，請注意：
        - 描述請簡潔、具體、明確。
        - 善用條列式敘述、圖片、或操作流程圖。
        - 若有設計文件或相關文件，請附上連結或檔案。
        - 建議先在討論區確認是否有類似提案。
        - 可以使用 Markdown 格式來美化說明。

  - type: textarea
    id: feature-description
    attributes:
      label: 📝 理由描述 Feature Description
      description: |
        [必填] 描述提議新功能的理由與價值。

        建議說明：
        - 此功能解決什麼問題？
        - 誰會受益於此功能？
        - 為什麼現在需要此功能？
      placeholder: 這個功能可以幫助使用者...
    validations:
      required: true

  - type: textarea
    id: suggested-solution
    attributes:
      label: ✨ 功能描述 Suggested Solution
      description: |
        [必填] 描述需求、流程、或/與 設計。

        建議包含：
        ## 功能需求
        1. 核心功能項目
        2. 次要功能項目
        3. 限制條件

        ## 使用流程
        1. 使用者操作步驟
        2. 系統回應行為
        3. 錯誤處理方式

        ## 介面設計
        - 可附上 mockup、線框圖
        - 說明主要操作介面
        - 描述使用者互動方式
      placeholder: 請詳細描述功能的運作方式...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 🎯 優先程度 Priority
      description: 請評估此功能的優先程度
      options:
        - 高 High (核心功能/重大改進)
        - 中 Medium (重要功能/明顯改進)
        - 低 Low (次要功能/小幅改進)
    validations:
      required: true

  - type: textarea
    id: alternative
    attributes:
      label: 💡其他替代方案 Alternative
      description: |
        [選填] 在此討論其他替代方案的可能性。

        建議說明：
        - 替代方案的優缺點
        - 為何選擇目前提案而非替代方案
        - 是否有暫時性的解決方案
      placeholder: 其他可能的解決方案包括...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 備註事項 Additional Context
      description: |
        [選填] 描述其他須注意事項，例如：
        - 技術相依性
        - 效能考量
        - 安全性議題
        - 維護成本
        - 預期困難
      placeholder: 實作此功能時需要注意...
    validations:
      required: false
